name: CI

on:
    push: 
        branches:
            - development
    pull_request:
        branches:
            - development

jobs:
    integration-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Set up Docker
              uses: docker/setup-buildx-action@v3
            
            - name: Run integration tests
              run: |
                docker compose -f docker-compose.integration.yml up \
                --build \
                --abort-on-container-exit \
                --exit-code-from test_runner

    build-and-push:
      runs-on: ubuntu-latest
      needs: integration-test
      if: github.event_name == 'push' && github.ref == 'refs/heads/development'

      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ${{secrets.AWS_DEFAULT_REGION}}

        - name: Login to ECR
          run: |
            aws ecr get-login-password | docker login \
              --username AWS \
              --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com

        - name: Build Production Image
          run: |
            docker build \
            --target production \
            -t ${{secrets.ECR_REPOSITORY}}:${{github.sha}} .

        - name: Tag Image
          run: |
            docker tag ${{secrets.ECR_REPOSITORY}}:${{github.sha}} \
            ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com/${{secrets.ECR_REPOSITORY}}:${{github.sha}}

        - name: Push Image
          run: |
            docker push \
            ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

    deploy:
      runs-on: ubuntu-latest
      needs: build-and-push
      if: github.ref == 'refs/heads/development'

      steps:
        - name: Deploy to EC2
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{secrets.EC2_HOST}}
            username: ${{secrets.EC2_USER}}
            key: ${{secrets.EC2_SSH_KEY}}
            script: |
              set -e

              echo "Changing to Proect directory"
              cd /var/www/docflow_api/

              echo "Logging to ECR"
              aws ecr get-login-password --region ${{secrets.AWS_DEFAULT_REGION}} \
              | docker login \
                --username AWS \
                --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com

                echo "Pulling Image"
                docker pull \
                ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com/${{secrets.ECR_REPOSITORY}}:${{github.sha}}

                echo "Stopping old container"
                docker stop worker || true
                docker rm worker || true

                echo "Starting old container"
                docker run -d \
                  --name worker \
                  --restart unless-stopped \
                  --env-file .env \
                  ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_DEFAULT_REGION}}.amazonaws.com/${{secrets.ECR_REPOSITORY}}:${{github.sha}}

                echo "Deployment completed"

